#!/usr/bin/env bash

# Do whatever here at server directory
# or we ain't doing nothing
cd "$(dirname "$0")" || exit

source "./utils/log.sh"

source "./utils/setup.sh"
source "./utils/clean.sh"
source "./utils/update.sh"
source "./utils/launch.sh"
source "./utils/backup.sh"

_help() {
    _log "HELP" "Usage: ${0} [options] [command]"
    _log "HELP" "  add DEBUG=true to enable debug mode before command"
    _log "HELP" "  don't pass anything or pass JAVA args to run server"
    _log "HELP"
    _log "HELP" "Commands:"
    _log "HELP" "  help            Show this help message"
    _log "HELP" "  update          Update the server to latest (jq needed)"
    _log "HELP" "  setup           Setup server and generate files"
    _log "HELP" "  clean           Clean the server"
    _log "HELP" "  backup          Backup the server"
    _log "HELP"
    _log "HELP" "If no command is provided, the launcher will show help message."
    _log "HELP"
    _log "HELP" "Options:"
    _log "HELP" "  any options to pass for java command"
    _log "HELP"
    _log "HELP" "Example:"
    _log "HELP" "  ${0} help"
    _log "HELP" "  ${0} update"
    _log "HELP" "  ${0} setup"
    _log "HELP" "  ${0} clean"
    _log "HELP" "  ${0} backup"
    _log "HELP"
    _log "HELP" "Onee-chan, if you stuck, dm me on telegram (you know my username, right? :D)"
}

while true; do
    case "${1}" in
        help)
            _help
            exit 0
            ;;
        setup)
            _setup
            exit 0
            ;;
        update)
            _update
            exit 0
            ;;
        clean)
            _clean
            exit 0
            ;;
        backup)
            _backup
            exit 0
            ;;
        *)
            _launch "$@"
            exit 1
            ;;
    esac
done