version: '3.8'
name: cxsmxs

services:
  minecraft:
    container_name: cxsmxs
    build:
      context: ../
      dockerfile: docker/Dockerfile
    ports:
      - "25565:25565"
    volumes:
      - ../server:/minecraft/server
    restart: always